### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by mjsoftking** [zhheo/halo-theme-heolink#23]
- 由于`postSelect`不能选择为空，建议`to_post_radio`默认值设置为`false`，作为导航使用时，更多偏向于添加外链，而不是文章链接。
```
    - $formkit: radio
      name: to_post_radio
      label: 关联文章
      help: 控制此链接是否关联文章
      value: "true"
      options: 
        - label: 关联
          value: "true"
        - label: 不关联
          value: "false"
```
